name: Deploy website on push new tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 7.0 ]

    steps:
      - name: checkout bcrampon prod
        uses: actions/checkout@v3

      - name: Restore the Composer cache directory
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-'8.0'-composer-

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          version: 2.2
          php_version: 7.0.33
          dev: no
          args: --prefer-dist --no-interaction

      - name: Zip artifact for deployment
        run: zip -r release.zip website/app/* website/vendor/* website/wordpress-core/* -x ".git/*" -x ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: create or replace backup release
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: "[ ! -d ~/prod/website ] || rm -rf ~/prod/old_website ~/prod/website/vendor ~/prod/website/wordpress-core"

      - name: checkout bcrampon prod
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: unzip artifact for deployment
        run: |
         unzip -o release.zip

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./website
          remote_path: ~/prod
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: create new Symlink
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            ln -nsrf ~/prod/shared/.env ~/prod/website/.env
            ln -nsrf ~/prod/shared/uploads ~/prod/website/app/uploads
            ln -nsrf ~/prod/shared/cache ~/prod/website/app/cache
            ln -nsrf ~/prod/shared/w3tc-config ~/prod/website/app/w3tc-config
            rm ~/prod/website/.htaccess
            ln -nsrf ~/prod/shared/.htaccess ~/prod/website/.htaccess